CREATE SCHEMA secdev;
ALTER SCHEMA secdev OWNER TO postgres;
ALTER DATABASE secdev_data SET search_path to secdev, public;

CREATE ROLE admin SUPERUSER;
CREATE ROLE readwrite;
CREATE ROLE read;
 
CREATE USER uppdadmin WITH ENCRYPTED PASSWORD 'changeMe';
CREATE USER uppdread WITH ENCRYPTED PASSWORD 'changeMe';
CREATE USER uppdreadwrite WITH ENCRYPTED PASSWORD 'changeMe';

ALTER USER postgres WITH ENCRYPTED PASSWORD 'changeMe';
 
GRANT admin TO uppdadmin;
GRANT readwrite TO uppdreadwrite;
GRANT read TO uppdread;

GRANT USAGE ON SCHEMA secdev to admin;
GRANT USAGE ON SCHEMA secdev to readwrite;
GRANT USAGE ON SCHEMA secdev to read;

ALTER DEFAULT PRIVILEGES IN SCHEMA secdev
  GRANT SELECT ON TABLES TO uppdread;
ALTER DEFAULT PRIVILEGES IN SCHEMA secdev
  GRANT SELECT ON SEQUENCES TO uppdread;
ALTER DEFAULT PRIVILEGES IN SCHEMA secdev
  GRANT SELECT, INSERT, UPDATE ON TABLES TO uppdreadwrite;
ALTER DEFAULT PRIVILEGES IN SCHEMA secdev
  GRANT SELECT, UPDATE ON SEQUENCES TO uppdreadwrite;
